version: "3.8"
services:

  # Applications

  # Backing Services

  k8s12f-postgres:
    image: "postgres:14.3"
    container_name: "k8s12f-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  k8s12f-redis:
    image: "redis:7.0"
    container_name: "k8s12f-redis"
    ports:
      - 6379:6379

  k8s12f-rabbitmq:
    image: rabbitmq:3.10-management
    container_name: k8s12f-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  k8s12f-keycloak:
    image: quay.io/keycloak/keycloak:18.0
    container_name: "k8s12f-keycloak"
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - 8080:8080